### ISSUE TITLE
Copies "nothing" on Chrome Version 56.0.2906.0 dev (64-bit)

### ISSUE THREAD

**Issue by ryantheleach** [owaisafaq/copier-js#1]
Using Chrome on Version 56.0.2906.0 dev (64-bit) "nothing" is copied.

e.g. I will paste what was copied to my clipboard from your demo into these quotes on gh.
```
"Copy Image to Clipboard via Javascript.         "
```
Pasting into Google Hangouts on Windows results in 
```
"         "
```

**Comment by owaisafaq** [comment]
The clipboard functionality works for softwares that support image pasting. Like MS Word, Powerpoint etc. The fallback automatically is the ALT value of the IMG tag. I tried with Chrome on both windows and linux and it works fine if you paste in the softwares that support image pasting.

**Comment by ryantheleach** [comment]
![image](https://cloud.githubusercontent.com/assets/141554/20259961/66f6686e-aaa7-11e6-8890-d7bd29074556.png)
That was pasted from mspaint, straight into the github text box. 

I really think that what you are doing is copying the html/formatting/rich text representation and not the image. Unless what I need is file pasting of some kind..

**Comment by kimsup10** [comment]
If I copies an image and pastes on messenger app(PC ver.), image is pasted on the app. However, when I click a image on your demo and paste it on messenger, text is pasted. As you said, even if I just click a image on your demo and then paste it on MS Powerpoint, the image is pasted. What is difference between them you think? I want to copy image and paste it on messenger

**Comment by owaisafaq** [comment]
The `document.execCommand('copy');` command copies two things. One is the markup of HTML that renders the image and second is the Alt text of the image. In whichever software it is possible to past the markup of image, the Clipboard allows that. Wherever it is restricted only to text, the image is not rendered. For me the client's requirement was to be able to paste the Image inside Ms Word and Powerpoint so it served the purpose.
