### ISSUE TITLE
It just copies the text!

### ISSUE THREAD

**Issue by Hydrock** [owaisafaq/copier-js#2]
It just copies the text!

**Comment by owaisafaq** [comment]
Try pasting what you copied in reply to this email.

**Comment by owaisafaq** [comment]
Did it work for you?

On Apr 25, 2017 2:10 PM, "Owais Afaq" <consult@owaisafaq.com> wrote:

Try pasting what you copied in reply to this email.

**Comment by ramezrafla** [comment]
Nope, it does not work ... this is what we get in clipboard:
"Copy Image to Clipboard via Javascript.         "

**Comment by owaisafaq** [comment]
Try pasting it in the body of an email or a word document.

**Comment by atodd-geoplan** [comment]
"Copy Image to Clipboard via Javascript."         

Is all this copies. I would take it down. Save folk some time.

**Comment by owaisafaq** [comment]
Whatever field supports pasting images, it does. Otherwise reverts back to
the alt tag. Try pasting it in an email body or a word document.

**Comment by atodd-geoplan** [comment]
Works for Word and gmail

but not for:
Outlook
gimp
paint
github comments

**Comment by adrianbj** [comment]
It also works for CKEditor when it has a plugin that supports image pasting, so it definitely has its uses!
